# Generated by Django 3.2.9 on 2022-02-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='big_image',
            field=models.ImageField(blank=True, upload_to='_big_products_images', verbose_name='Изображение на гланую'),
        ),
    ]
